name: Build dylib for iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Theos environment
        run: |
          # 必要なツールをインストール
          sudo apt-get update
          sudo apt-get install -y clang curl git unzip lzma libssl-dev libcurl4-openssl-dev make

          # Theos をインストール
          git clone --recursive https://github.com/theos/theos.git /opt/theos

          # iOS SDK をインストール
          mkdir -p /opt/theos/sdks
          cd /opt/theos/sdks
          git clone https://github.com/theos/sdks.git .

          # Theos のパスを設定
          echo 'export THEOS=/opt/theos' >> $GITHUB_ENV
          echo 'export PATH=$PATH:/opt/theos/bin:/opt/theos/vendor/bin' >> $GITHUB_ENV

      - name: Build dylib
        run: |
          # 環境変数を設定
          export THEOS=/opt/theos
          export THEOS_MAKE_PATH=$THEOS/makefiles
          export TARGET=iphone:13.7:11.4
          export ARCHS=arm64
          export THEOS_PLATFORM_DEB_COMPRESSION_TYPE=gzip
          export DEBUG=0
          export STRIP=1
          export FINALPACKAGE=1

          # SDK 確認 (デバッグ用)
          ls -la /opt/theos/sdks

          # Dylib をビルド
          make -C .

      - name: Upload dylib build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dylib
          path: .theos/obj/iphone_arm64/H5GG.dylib
